---
# This is based on a nice explanation here: 

- name: unattended-upgrades | Install
  package: name=unattended-upgrades state=present
  tags: [auto-updates]
  when: debian10

- name: apt-listchanges | Install
  package: name=apt-listchanges state=present
  tags: [auto-updates]
  when: debian10

- name: unattended-upgrades | Configure
  ansible.builtin.debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: true
    vtype: boolean
  tags: [auto-updates]
  when: debian10
