---
# Install and enable fail2ban

- name: fail2ban | Install
  package: name=fail2ban state=present
  tags: [fail2ban]

- name: fail2ban | Configure
  template: src=local-sshd.conf.j2 dest=/etc/fail2ban/jail.d/local-sshd.conf
  register: jails
  notify: [Reload fail2ban]
  tags: [fail2ban]

- name: fail2ban | Enable, Start
  service: name=fail2ban state=started enabled=yes
  tags: [fail2ban]
