---
- name: ssh | Check we aren't using root to provision
  shell: printenv SUDO_USER
  register: sudo_user
  changed_when: false
  failed_when: sudo_user.stdout == '' or sudo_user.stdout == 'root'
  tags: [ssh, check]

- name: ssh | Disallow passwords and root login
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config.d/90-ansible-lockdown.conf mode=0640
  register: sshd_config
  notify: [Reload sshd]
  tags: [ssh]
