---
- name: Reload postfix
  service: name=postfix state=reloaded

- name: Update relay_password
  command: postmap /etc/postfix/relay_password
  listen: Update DBs

- name: Update virtual
  command: postmap /etc/postfix/virtual
  listen: Update DBs
