---
# Update the variables here, then copy this to all.yml.
#
# SMTP host (host only) where we send all mail I use amazon in us-east, so I
# set this to email-smtp.us-east-1.amazonaws.com
relay_host: 
# Port to use on relay_host
relay_port: 587
# Authentication for relay host
relay_username: 
relay_password: 

# If we send email to something@<localhost>, where should it go?
# I set this to a personal email.
localhost_relay_email: 

# Emails sent from the command-line will appear to come from
# <hostname>.<domain>
# I set this to the common domain all my personal machines are in.
domain: 
