---
# Update the variables here, then copy this to all.yml.
#
# SMTP host (host only) where we send all mail I use amazon in us-east, so I
# set this to email-smtp.us-east-1.amazonaws.com
relay_host: 
# Port to use on relay_host
relay_port: 587
# Authentication for relay host
relay_username: 
relay_password: 

# If we send email to something@<localhost>, where should it go?
# I set this to a personal email.
localhost_relay_email: 

# Emails sent from the command-line will appear to come from
# <hostname>.<domain>
# I set this to the common domain all my personal machines are in.
domain: 

# This lets you listen on extra interfaces if you want to. BEWARE of listening
# on public interfaces! With this configuration, you must be *both* listening on an interface and
# permitting the source address to relay mail. If you *are* listening on an
# interface and permitting an address range, you will be an open relay for that
# address range.
# 
# This is intended for things like docker hosts that want to relay mail from
# containers.
listen_interfaces: loopback-only
extra_permitted_networks: 
# Here's an example for docker:
# Get this address from the address of the docker0 interface:
# extra_listen_interfaces: 172.17.0.1
# This is a private network range:
# https://www.arin.net/reference/research/statistics/address_filters/
#extra_permitted_networks: 172.16.0.0/12
