---
- name: Install postfix
  package: name=postfix state=present
  tags: [pkgs]

- name: Install SASL libs - RHEL/CentOS
  package: name=cyrus-sasl-plain state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags: [pkgs]

- name: Install SASL libs - Debian/Ubuntu
  package: name=libsasl2-2 state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 
  tags: [pkgs]

