---
- name: Reload sshd
  service: name=sshd state=reloaded

- name: Reload iptables
  shell: /sbin/lockdown-iptables-restore

- name: Reload sysctls
  shell: sysctl --system

- name: Reload wireguard
  service: name=wg-quick@wg0 state=reloaded
