---
# This is based on a nice explanation here: 
# https://serversforhackers.com/c/automatic-security-updates-centos

# yum-cron for centos 7
- name: yum-cron | Install
  package: name=yum-cron state=present
  tags: [auto-updates]
  when: centos7

- name: yum-cron | Configure
  template: src=yum-cron.conf.j2 dest=/etc/yum/yum-cron.conf
  tags: [auto-updates]
  when: centos7

- name: yum-cron | Enable, Start
  service: name=yum-cron state=started enabled=yes
  tags: [auto-updates]
  when: centos7

# dnf-automatic for centos 8
- name: dnf-automatic | Install
  package: name=dnf-automatic state=present
  tags: [auto-updates]
  when: centos8

- name: dnf-automaticc | Configure
  template: src=dnf-automatic.conf.j2 dest=/etc/dnf/automatic.conf
  tags: [auto-updates]
  when: centos8

- name: dnf-automatic | Enable, Start
  service: name=dnf-automatic state=started enabled=yes
  tags: [auto-updates]
  when: centos8
