---
- name: Install (Ubuntu) | Signing key
  apt_key:
    id: 05CE15085FC09D18E99EFB22684A14CF2582E0C5
    url: https://repos.influxdata.com/influxdb.key
    state: present
  when: is_ubuntu

- name: Install (Ubuntu) | Apt Repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
  when: is_ubuntu

- name: Install (CentOS) | YUM Repository
  yum_repository:
    name: "influxdb"
    description: "InfluxDB Repository - RHEL $releasever"
    baseurl: "https://repos.influxdata.com/rhel/$releasever/$basearch/stable"
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
  when: is_centos

- name: Install | Package
  package:
    name: telegraf
    state: present

- name: Configure
  copy:
    src: telegraf.conf
    dest: "/etc/telegraf/telegraf.conf"
  register: telegraf_conf

- name: Service | Start
  systemd:
    state: started
    daemon_reload: yes
    name: telegraf
  register: telegraf_start

- name: Service | Restart
  systemd:
    state: restarted
    name: telegraf
  when:
    - telegraf_conf.changed
    - not telegraf_start.changed
